# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'birthday' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for birthday
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'birthday-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'birthdayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
